version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.4.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus:v2.37.6
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus:/tmp/conf
    command:
      - '--config.file=/tmp/conf/prometheus.yml'
  my-exporter:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${PWD}/metrics:/usr/share/nginx/html/metrics:ro
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
