#!/bin/bash

function processing {
	case $1 in
		1) sort -k9 ../04/access_*.log ;;
		2) awk '{print $1}' ../04/access_*.log | uniq ;;
		3) awk '$9 ~ /[4-5][0][0-4]/' ../04/access_*.log ;;
		4) awk '$9 ~ /[4-5][0][0-4]/' ../04/access_*.log | awk '{print $1}' | uniq ;;
	esac
}
