#!/bin/bash

check_arg_1() {
        if ! [[ $1 =~ ^[a-zA-Z]{2,7}$ ]]; then
                echo "Error: arg_3: The list must contain 2-7 letters"
                exit 1
        fi
}

check_arg_2() {
        if ! [[ $1 =~ ^[a-zA-Z]{2,7}[.][a-zA-Z]{2,3}$ ]]; then
                echo "Error: arg_5: Wrong template"
                exit 1
        fi
}

check_arg_3() {
        if ! [[ $1 =~ ^[1-9][0-9]?[0]?MB$ ]]; then
                echo "Error: arg_6: Wrong size"
                exit 1
        fi
}

check_path(){
	if grep -q '/bin/' <<< $path || grep -q '/sbin/' <<< $path; then
		echo "Error: Script don't work in bin directories"
		exit 1
	fi
}

validating() {
	check_arg_1 $1
        check_arg_2 $2
        check_arg_3 $3
	check_path
}
