version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.4.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus:v2.37.6
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus:/tmp/conf
    command:
      - '--config.file=/tmp/conf/prometheus.yml'
  node-exporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
