{
 "title": "My exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "disk_capacity{job=\"custom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_space_used{job=\"custom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_space_free{job=\"custom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "memory_total{job=\"custom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_free{job=\"custom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_used{job=\"custom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cpu_usage{job=\"custom\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}